on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.9.3" # The Go version to download (if necessary) and use.
      - run: |
          git clone https://github.com/khanhas/spicetify-cli
          cd spicetify-cli
          go build -o spicetify.exe
          dir
          powershell.exe Compress-Archive -Path * -Update -DestinationPath build.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Daily build"
          files: spicetify-cli/build.zip
