on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
        env:
          GOOS: windows
          GOARCH: amd64
        with:
          go-version: "^1.9.3" # The Go version to download (if necessary) and use.
      - run: |
          git clone https://github.com/khanhas/spicetify-cli
          cd spicetify-cli
          go build -o spicetify.exe
          zip -r -v build.zip Extensions jsHelper Themes globals.d.ts css-map.json spicetify.exe
